Fix whitespaces

diff --git a/gerrit b/gerrit
--- a/gerrit
+++ b/gerrit
@@ -8,7 +8,7 @@ remote_port=
 project=
 
 show_usage() {
-	cat <<EOF
+  cat <<EOF
 Usage:
 
   gerrit <command>
@@ -80,24 +80,24 @@ EOF
 }
 
 die() {
-	echo -e "=========\n  ERROR\n========="
-	echo -e "${@}"
-	exit
+  echo -e "=========\n  ERROR\n========="
+  echo -e "${@}"
+  exit
 }
 
 ask() {
 
-	local question=$1 default=$2
+  local question=$1 default=$2
 
-	if [[ -n $default ]]; then
-		question="$question [$default]"
-	fi
+  if [[ -n $default ]]; then
+    question="$question [$default]"
+  fi
 
-	read -p "$question "
+  read -p "$question "
 
-	if [[ -z $REPLY ]]; then
-		REPLY="$default"
-	fi
+  if [[ -z $REPLY ]]; then
+    REPLY="$default"
+  fi
 
 }
 
@@ -113,25 +113,25 @@ confirm() {
     die "WHAT?! confirm doesn't know '$default'"
   fi
 
-	while true; do
+  while true; do
 
-		ask "$question $prompt "
+    ask "$question $prompt "
 
-		REPLY=$(lowercase "$REPLY")
+    REPLY=$(lowercase "$REPLY")
 
-		if [[ $REPLY == "yes" ]]; then
-			REPLY=y
-		elif [[ $REPLY == "no" ]]; then
-			REPLY=n
+    if [[ $REPLY == "yes" ]]; then
+      REPLY=y
+    elif [[ $REPLY == "no" ]]; then
+      REPLY=n
     elif [[ -z $REPLY ]]; then
       REPLY="$default"
-		fi
+    fi
 
-		if [[ $REPLY =~ [yn] ]]; then
-			break
-		fi
+    if [[ $REPLY =~ [yn] ]]; then
+      break
+    fi
 
-	done
+  done
 
 }
 
@@ -144,7 +144,7 @@ uppercase() {
 }
 
 ssh_gerrit() {
-	ssh -p $remote_port "$remote_user@$remote_host" -- gerrit $1
+  ssh -p $remote_port "$remote_user@$remote_host" -- gerrit $1
 }
 
 get_all_gerrit_remote_names() {
@@ -152,89 +152,89 @@ get_all_gerrit_remote_names() {
 }
 
 get_gerrit_remote_config() {
-	local name="$1"
+  local name="$1"
 
-	remote_name="$name"
-	remote_user=$(git config "gerrit.$name.user")
-	remote_host=$(git config "gerrit.$name.host")
-	remote_port=$(git config "gerrit.$name.port")
+  remote_name="$name"
+  remote_user=$(git config "gerrit.$name.user")
+  remote_host=$(git config "gerrit.$name.host")
+  remote_port=$(git config "gerrit.$name.port")
 
-	if [[ -z $remote_host ]]; then
+  if [[ -z $remote_host ]]; then
     confirm "I couldn't find a config for \"$name\", would you like to create one?" 'y'
     if [[ $REPLY == "y" ]]; then
       setup_gerrit_config "$name"
     else
       exit
     fi
-	fi
+  fi
 }
 
 get_repo_remote_config() {
-	check_in_git_repo
-	local branch=${1:-"master"}
-	remote_name=$(git config "branch.$branch.remote")
-	local remote_url=$(git config "remote.$remote_name.url" | sed -e 's|^ssh://||')
-	remote_port=$(echo $remote_url | sed -e 's|^.*:||' -e 's|/.*$||')
-	remote_host=$(echo $remote_url | sed -e 's|^.*@||' -e 's|:.*$||')
-	remote_user=$(echo $remote_url | sed -e 's|@.*$||')
-	project=$(echo $remote_url | sed -e 's|^[^/]*/||' -e 's|\.git||')
+  check_in_git_repo
+  local branch=${1:-"master"}
+  remote_name=$(git config "branch.$branch.remote")
+  local remote_url=$(git config "remote.$remote_name.url" | sed -e 's|^ssh://||')
+  remote_port=$(echo $remote_url | sed -e 's|^.*:||' -e 's|/.*$||')
+  remote_host=$(echo $remote_url | sed -e 's|^.*@||' -e 's|:.*$||')
+  remote_user=$(echo $remote_url | sed -e 's|@.*$||')
+  project=$(echo $remote_url | sed -e 's|^[^/]*/||' -e 's|\.git||')
 }
 
 setup_gerrit_config() {
-	local name="$1"
+  local name="$1"
 
-	if [[ -n $(git config --get-regexp "^gerrit.$name") ]]; then
-		confirm "A gerrit remote config for \"$name\" already exists, edit?" "Y"
-		if [[ $REPLY == "n" ]]; then
-			exit
-		fi
-		get_gerrit_remote_config $name
-	fi
+  if [[ -n $(git config --get-regexp "^gerrit.$name") ]]; then
+    confirm "A gerrit remote config for \"$name\" already exists, edit?" "Y"
+    if [[ $REPLY == "n" ]]; then
+      exit
+    fi
+    get_gerrit_remote_config $name
+  fi
 
-	echo -e "\nSetting up gerrit remote config for \"$name\""
+  echo -e "\nSetting up gerrit remote config for \"$name\""
 
-	ask "Remote Gerrit Host:" "$remote_host"
-	remote_host="$REPLY"
+  ask "Remote Gerrit Host:" "$remote_host"
+  remote_host="$REPLY"
 
-	ask "Remote Gerrit Username:" "$remote_user"
-	remote_user="$REPLY"
+  ask "Remote Gerrit Username:" "$remote_user"
+  remote_user="$REPLY"
 
-	ask "Remote Gerrit Port:" ${remote_port:-29418}
-	remote_port="$REPLY"
+  ask "Remote Gerrit Port:" ${remote_port:-29418}
+  remote_port="$REPLY"
 
-	git config --global "gerrit.$name.host" "$remote_host"
-	git config --global "gerrit.$name.user" "$remote_user"
-	git config --global "gerrit.$name.port" "$remote_port"
+  git config --global "gerrit.$name.host" "$remote_host"
+  git config --global "gerrit.$name.user" "$remote_user"
+  git config --global "gerrit.$name.port" "$remote_port"
 
   echo -e "\nSuccess!\n"
 }
 
 setup_commit_msg_hook() {
-	if [[ ! -d .git/hooks ]]; then
-		echo "Could not find .git/hooks directory to setup commit-msg hook"
-		return
-	fi
-	scp -p -P "$remote_port" "$remote_user@$remote_host:hooks/commit-msg" ".git/hooks/"
+  if [[ ! -d .git/hooks ]]; then
+    echo "Could not find .git/hooks directory to setup commit-msg hook"
+    return
+  fi
+  scp -p -P "$remote_port" "$remote_user@$remote_host:hooks/commit-msg" ".git/hooks/"
 }
 
 get_projects() {
-	get_gerrit_remote_config "$1"
+  get_gerrit_remote_config "$1"
   ssh_gerrit "ls-projects"
 }
 
 in_git_repo() {
-	git rev-parse --git-dir &> /dev/null
+  git rev-parse --git-dir &> /dev/null
 }
 
 check_in_git_repo() {
-	if ! in_git_repo; then
-		die "You must be in a git repository to run that command."
-	fi
+  if ! in_git_repo; then
+    die "You must be in a git repository to run that command."
+  fi
 }
 
 case $op in
 
-	ssh)
+  ssh)
 
     remote_name="$2"
 
@@ -251,44 +251,44 @@ case $op in
 
     fi
 
-		get_gerrit_remote_config "$remote_name"
+    get_gerrit_remote_config "$remote_name"
 
     ssh_gerrit "$ssh_command"
-		;;
+    ;;
 
   pubmit|ninja)
     gerrit push && gerrit submit "auto-submit"
     ;;
 
-	push|draft)
+  push|draft)
 
-		check_in_git_repo
+    check_in_git_repo
 
-		get_repo_remote_config
+    get_repo_remote_config
 
-		if [[ $op = "push" ]]; then
-			type="for"
-		elif [[ $op = "draft" ]]; then
-			type="drafts"
-		fi
+    if [[ $op = "push" ]]; then
+      type="for"
+    elif [[ $op = "draft" ]]; then
+      type="drafts"
+    fi
 
-		if [[ $# < 2 ]]; then
-			branch="master"
-		else
-			branch=$2
-		fi
+    if [[ $# < 2 ]]; then
+      branch="master"
+    else
+      branch=$2
+    fi
 
-		topic=$(git symbolic-ref HEAD | cut -d'/' -f 3)
+    topic=$(git symbolic-ref HEAD | cut -d'/' -f 3)
 
-		ref="refs/$type/$branch/$topic"
+    ref="refs/$type/$branch/$topic"
 
-		echo "Pushing to $remote_name ($ref)"
+    echo "Pushing to $remote_name ($ref)"
 
-		git push $remote_name "HEAD:$ref"
+    git push $remote_name "HEAD:$ref"
 
-		;;
+    ;;
 
-	config)
+  config)
 
     all_gerrit_names="$2"
 
@@ -318,57 +318,57 @@ case $op in
 
     done
 
-		;;
+    ;;
 
-	clone)
+  clone)
 
-		gerrit_name="$2"
-		project="$3"
-		folder="${4:-$project}"
+    gerrit_name="$2"
+    project="$3"
+    folder="${4:-$project}"
 
     if [[ -z $gerrit_name ]]; then
       die "A gerrit config name is required for this command."
     fi
 
-		get_gerrit_remote_config "$gerrit_name"
+    get_gerrit_remote_config "$gerrit_name"
 
-		if [[ -z $project ]]; then
-			echo "Which project would you like to clone?"
-			echo "[$remote_name]"
-			get_projects "$remote_name" | awk '{ print "> ", $0 }'
-			ask "Project:"
-			if [[ -z $REPLY ]]; then exit; fi
-			project="$REPLY"
-			ask "Into which folder?" "$project"
-			folder="$REPLY"
-		fi
+    if [[ -z $project ]]; then
+      echo "Which project would you like to clone?"
+      echo "[$remote_name]"
+      get_projects "$remote_name" | awk '{ print "> ", $0 }'
+      ask "Project:"
+      if [[ -z $REPLY ]]; then exit; fi
+      project="$REPLY"
+      ask "Into which folder?" "$project"
+      folder="$REPLY"
+    fi
 
-		if [[ -e "$folder" ]]; then
-			die "File or folder $folder already exists."
-		fi
+    if [[ -e "$folder" ]]; then
+      die "File or folder $folder already exists."
+    fi
 
 
-		echo "Cloning project $project from $remote_name into folder $folder..."
+    echo "Cloning project $project from $remote_name into folder $folder..."
 
-		git clone "ssh://$remote_user@$remote_host:$remote_port/$project.git" "$folder"
+    git clone "ssh://$remote_user@$remote_host:$remote_port/$project.git" "$folder"
 
-		if [[ $? -eq 0 ]]; then
+    if [[ $? -eq 0 ]]; then
 
-			cd "$folder"
+      cd "$folder"
 
       git config remote.origin.gerrit "$remote_name"
 
-			echo "Setting up commit-msg hook..."
+      echo "Setting up commit-msg hook..."
 
-			setup_commit_msg_hook
+      setup_commit_msg_hook
 
-			echo "Done!"
+      echo "Done!"
 
-		fi
+    fi
 
-		;;
+    ;;
 
-	projects)
+  projects)
 
     gerrit_name="$2"
 
@@ -378,57 +378,57 @@ case $op in
 
     get_projects "$gerrit_name"
 
-		;;
+    ;;
 
-	st|status)
+  st|status)
 
-		check_in_git_repo
+    check_in_git_repo
 
-		get_repo_remote_config
+    get_repo_remote_config
 
-		query="status:open project:$project"
+    query="status:open project:$project"
 
-		if [[ $2 != "all" ]]; then
-			query="$query reviewer:$remote_user"
-		fi
+    if [[ $2 != "all" ]]; then
+      query="$query reviewer:$remote_user"
+    fi
 
-		result=$(ssh_gerrit "query '$query'")
+    result=$(ssh_gerrit "query '$query'")
 
-		number=
-		owner=
-		subject=
-		topic=
+    number=
+    owner=
+    subject=
+    topic=
 
-		while read line; do
-			if [[ $line =~ ^\s*$ ]]; then
-				echo "$number [$topic] \"$subject\" ($owner)"
-				number=
-				owner=
-				subject=
-				topic=
-			elif [[ $line =~ ^number ]]; then
-				number=$(echo $line | sed -e 's|^.*: *||')
-			elif [[ $line =~ ^name ]]; then
-				owner=$(echo $line | sed -e 's|^.*: *||')
-			elif [[ $line =~ ^subject ]]; then
-				subject=$(echo $line | sed -e 's|^.*: *||')
-			elif [[ $line =~ ^topic ]]; then
-				topic=$(echo $line | sed -e 's|^.*: *||')
-				#else
-				#echo "$line"
-			fi
+    while read line; do
+      if [[ $line =~ ^\s*$ ]]; then
+        echo "$number [$topic] \"$subject\" ($owner)"
+        number=
+        owner=
+        subject=
+        topic=
+      elif [[ $line =~ ^number ]]; then
+        number=$(echo $line | sed -e 's|^.*: *||')
+      elif [[ $line =~ ^name ]]; then
+        owner=$(echo $line | sed -e 's|^.*: *||')
+      elif [[ $line =~ ^subject ]]; then
+        subject=$(echo $line | sed -e 's|^.*: *||')
+      elif [[ $line =~ ^topic ]]; then
+        topic=$(echo $line | sed -e 's|^.*: *||')
+        #else
+        #echo "$line"
+      fi
 
-		done < <(echo "$result")
+    done < <(echo "$result")
 
-		;;
+    ;;
 
-	review|submit|abandon)
+  review|submit|abandon)
 
-		check_in_git_repo
+    check_in_git_repo
 
-		get_repo_remote_config
+    get_repo_remote_config
 
-		commit=$(git rev-list --max-count=1 HEAD)
+    commit=$(git rev-list --max-count=1 HEAD)
 
     action=
     verified=
@@ -480,17 +480,17 @@ case $op in
       message="--message \"$message\""
     fi
 
-		ssh_gerrit "review $action --project \"$project\" $verified $code_review $message $commit"
+    ssh_gerrit "review $action --project \"$project\" $verified $code_review $message $commit"
 
-		;;
+    ;;
 
-	assign)
+  assign)
 
-		check_in_git_repo
+    check_in_git_repo
 
-		get_repo_remote_config
+    get_repo_remote_config
 
-		commit=$(git rev-list --max-count=1 HEAD)
+    commit=$(git rev-list --max-count=1 HEAD)
 
     shift
 
@@ -504,7 +504,7 @@ case $op in
 
     done
 
-		;;
+    ;;
 
   checkout|co|recheckout|reco)
 
@@ -513,9 +513,9 @@ case $op in
       is_reco="yes"
     fi
 
-		check_in_git_repo
+    check_in_git_repo
 
-		get_repo_remote_config
+    get_repo_remote_config
 
     if [[ $is_reco ]]; then
       target=$(git symbolic-ref HEAD | cut -d'/' -f 3)
@@ -552,25 +552,25 @@ case $op in
 
     fi
 
-		hash=$(($change_id % 100))
-		case $hash in
-			[0-9]) hash="0$hash" ;;
-		esac
+    hash=$(($change_id % 100))
+    case $hash in
+      [0-9]) hash="0$hash" ;;
+    esac
 
-		ref="refs/changes/$hash/$change_id"
+    ref="refs/changes/$hash/$change_id"
 
     if [[ $is_reco && $# -ge 2 ]]; then
       patch_id=$2
-		elif [[ $# -ge 3 ]]; then
-			patch_id=$3
-		else
-			echo "Getting latest patchset..."
-			patch_id=$(git ls-remote $remote_name "$ref/*" | sed -n 's|.*/||p' | sort -n | tail -n 1)
-		fi
+    elif [[ $# -ge 3 ]]; then
+      patch_id=$3
+    else
+      echo "Getting latest patchset..."
+      patch_id=$(git ls-remote $remote_name "$ref/*" | sed -n 's|.*/||p' | sort -n | tail -n 1)
+    fi
 
-		ref="$ref/$patch_id"
+    ref="$ref/$patch_id"
 
-		echo "Refspec is $ref"
+    echo "Refspec is $ref"
 
     git fetch $remote_name $ref
 
@@ -578,17 +578,22 @@ case $op in
 
       # TODO: Ensure no changes before changing branch
       if [[ $topic == "master" ]]; then
+
         echo "Patch topic is \"master\", therefore staying on detached head."
+
       elif [[ -n $topic && $(git branch | grep "$topic") ]]; then
+
         if [[ $is_reco ]]; then
           REPLY='y'
         else
           ask "Branch with name $topic already exists, overwrite?"
         fi
+
         if [[ $REPLY ==  'y' ]]; then
           git checkout master
           git branch -D "$topic"
         fi
+
       fi
 
       if [[ -z $topic || $(git branch | grep "$topic") ]]; then
